### ISSUE TITLE
Error `'NoneType' object has no attribute 'get'`

### ISSUE THREAD

**Issue by mcuadros** [bblfsh/python-driver#119]
https://github.com/django/django/blob/master/django/urls/converters.py

```
File: [Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/python_driver/requestprocessor.py", line 144, in process_request
    ast = AstImprover(code, orig_ast).parse()
  File "/usr/lib/python3.6/site-packages/python_driver/astimprove.py", line 419, in parse
    res = self.visit(self._astdict, root=True)
  File "/usr/lib/python3.6/site-packages/python_driver/astimprove.py", line 432, in visit
    visit_result = meth(node)
  File "/usr/lib/python3.6/site-packages/python_driver/astimprove.py", line 508, in visit_other
    node[field] = meth(node[field])
  File "/usr/lib/python3.6/site-packages/python_driver/astimprove.py", line 515, in visit_other_field
    return [self.visit(x) for x in node]
  File "/usr/lib/python3.6/site-packages/python_driver/astimprove.py", line 515, in <listcomp>
    return [self.visit(x) for x in node]
  File "/usr/lib/python3.6/site-packages/python_driver/astimprove.py", line 432, in visit
    visit_result = meth(node)
  File "/usr/lib/python3.6/site-packages/python_driver/astimprove.py", line 508, in visit_other
    node[field] = meth(node[field])
  File "/usr/lib/python3.6/site-packages/python_driver/astimprove.py", line 515, in visit_other_field
    return [self.visit(x) for x in node]
  File "/usr/lib/python3.6/site-packages/python_driver/astimprove.py", line 515, in <listcomp>
    return [self.visit(x) for x in node]
  File "/usr/lib/python3.6/site-packages/python_driver/astimprove.py", line 432, in visit
    visit_result = meth(node)
  File "/usr/lib/python3.6/site-packages/python_driver/astimprove.py", line 508, in visit_other
    node[field] = meth(node[field])
  File "/usr/lib/python3.6/site-packages/python_driver/astimprove.py", line 513, in visit_other_field
    return self.visit(node)
  File "/usr/lib/python3.6/site-packages/python_driver/astimprove.py", line 432, in visit
    visit_result = meth(node)
  File "/usr/lib/python3.6/site-packages/python_driver/astimprove.py", line 508, in visit_other
    node[field] = meth(node[field])
  File "/usr/lib/python3.6/site-packages/python_driver/astimprove.py", line 515, in visit_other_field
    return [self.visit(x) for x in node]
  File "/usr/lib/python3.6/site-packages/python_driver/astimprove.py", line 515, in <listcomp>
    return [self.visit(x) for x in node]
  File "/usr/lib/python3.6/site-packages/python_driver/astimprove.py", line 427, in visit
    ctx = node.get("ctx")
AttributeError: 'NoneType' object has no attribute 'get'
]
```

**Comment by juanjux** [comment]
Fixed by #120.
