### ISSUE TITLE
Exception deserializing message in BblfshClient.parse()

### ISSUE THREAD

**Issue by zurk** [bblfsh/python-driver#46]
I try to run bblfsh python client and it fails (change end point if you need):
```python
from bblfsh import BblfshClient
BblfshClient("172.17.0.1:9432").parse('./TickType.py', language='Python', )
```
Here is file example: [TickType.py.zip](https://github.com/bblfsh/python-driver/files/1176940/TickType.py.zip)

The output I get:
```
ERROR:root:Exception deserializing message!
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/grpc/_common.py", line 129, in _transform
    return transformer(message)
google.protobuf.message.DecodeError: Error parsing message
Traceback (most recent call last):
  File "bug_exapmle.py", line 3, in <module>
    BblfshClient("172.17.0.1:9432").parse('./temp/TickType.py', language='Python', )
  File "/usr/local/lib/python3.5/dist-packages/bblfsh/client.py", line 58, in parse
    response = self._stub.Parse(request, timeout=timeout)
  File "/usr/local/lib/python3.5/dist-packages/grpc/_channel.py", line 507, in __call__
    return _end_unary_response_blocking(state, call, False, deadline)
  File "/usr/local/lib/python3.5/dist-packages/grpc/_channel.py", line 455, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with (StatusCode.INTERNAL, Exception deserializing response!)>
```

And bblfsh server does not fails in this example if I run it directly.
Seems to be some problem in grpc module...

**Comment by abeaumont** [comment]
Probably a duplicate of https://github.com/bblfsh/server/issues/59

**Comment by zurk** [comment]
Yes, it is. I found a solution, add the comment with useful script here https://github.com/bblfsh/server/issues/59#issuecomment-318125752
